# Generated by Django 6.0.4 on 2026-04-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('arrival_time', models.TimeField()),
                ('likely_late', models.BooleanField(default=False)),
                ('potluck_item', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['arrival_time', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_non_blank_rsvp_email')],
            },
        ),
    ]
