# Generated by Django 6.0.4 on 2026-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='attendance_status',
            field=models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe')], default='going', max_length=16),
        ),
    ]
