# Generated by Django 6.0.4 on 2026-04-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_rsvp_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
