# Generated by Django 6.0.4 on 2026-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_rsvp_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='attendance_status',
            field=models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('cant_go', "Can't Go")], default='going', max_length=16),
        ),
    ]
