# Generated by Django 6.0.4 on 2026-04-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_alter_rsvp_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
